### ISSUE TITLE
Rendering bug.

### ISSUE THREAD

**Issue by Mourtz** [JosefZIla/bash-drawille#2]
The pixel matrix has some minor bugs. I have noticed that the problem occurs only in X dimension. For example, some rows consist of 130 pixels, while another consist of 128. Probably that's the reason why they are blanks when drawing the vertical lines of the border.

**Comment by JosefZIla** [comment]
I dont see this problem on my system , can you upload a picture of it? These look fine to me:

![screen](https://cloud.githubusercontent.com/assets/6953816/8412681/afeada90-1e8b-11e5-9b4b-107580d23cf2.png)

![screen2](https://cloud.githubusercontent.com/assets/6953816/8412812/a9545890-1e8c-11e5-8e6c-5cb736c09006.png)

**Comment by Mourtz** [comment]
![screenshot from 2015-06-30 00 21 35](https://cloud.githubusercontent.com/assets/6444818/8418878/7f3f6036-1ebe-11e5-9b0d-b0106320350c.png)

The bitmap seems fine as you can see, there are still gaps though.
When I tried to render a cube using draw_line function I had to change the origin of x sometimes  in
order to render a perfect shape.

I m gonna check it again.

**Comment by JosefZIla** [comment]
The gaps you see between each 4 lines are probably caused by your font, every braille character is basically 8 dots arranged in 2x4 pattern, but the font decides where those dots are in the character - if there is some space on top or bottom, the character in next line will look like it is some distance away, there is no way I can control that.
